services:
  web:
    build: .  # Construir a partir do Dockerfile na pasta atual
    ports:
      - "${WEB_PORT}:8080"  # Porta configurada via .env
    volumes:
      - .:/app  # Montar o diretório local para desenvolvimento
    env_file:
      - .env
    environment:
      - ENV=development
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"  # Porta configurada via .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_PORT}:80"  # Porta configurada via .env
    depends_on:
      - postgresdb

volumes:
  postgres_data:
