version: "3"

services:
  web:
    build: .  # Build the image using the Dockerfile in the current directory
    ports:
      - "8080:8080"  # Expose port 8080 in the container to port 8080 on your local machine
    volumes:
      - .:/app  # Mount your local directory into the container
    environment:
      - ENV=development  # Set environment variables (optional)
      - DB_HOST=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"